# ==============================================================================
# Kea Device Client configuration
# ==============================================================================

# ==============================================================================
# Device Configuration

# The Device ID is a unique UUID for the device within Kea
# It is a required configuration item
device-id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

# ==============================================================================
# Location Input Configuration

# The driver describes how the client should obtain location information.
# Exactly one driver should be specified.
# The options are: tcp, serial
driver:
  # TCP socket driver
  tcp:
    host: 192.168.0.222
    port: 55555
  # Serial port driver
  #serial:
  #  port: /dev/ttyUSB0
  #  baud: 115200

# The format describes how the location data should be decoded.
# Exactly one driver should be specified.
# The options are: sbp, nmea
format:
  # Swift Binary Protocol (SBP) format
  sbp:
    # Include orientation information? Only enable if the device is capable of
    # outputting MSG_ORIENT_EULER
    orientation: false
  # NMEA format (no configuration options)
  #nmea:

# Decimate the location inputs by a constant factor
#decimate: 10

# ------------------------------------------------------------------------------
# Recipes:

# Typical GPS receiver connected over USB Serial
#driver:
#  serial:
#    port: /dev/ttyUSB0
#    baud: 115200
#format:
#  nmea:

# Piksi Multi / Duro / Starling connected over TCP
#driver:
#  tcp:
#    host: 192.168.0.222
#    port: 55555
#format:
#  sbp:
#    orientation: false

# Duro Inertial connected over TCP (with orientation)
#driver:
#  tcp:
#    host: 192.168.0.222
#    port: 55555
#format:
#  sbp:
#    orientation: true

# ==============================================================================
# Advanced Options
#
# (you shouldn't need to set these unless you have a specific reason to override
# the default values)

# Kea server configuration
#host: grpc.dev.kea.swiftnav.com
#host: grpc.staging.kea.swiftnav.com
#host: localhost
#port: 443
#port: 10000
#disable_tls: true
