name: Code Formatting and Linting
on:
  push:

env:
  #https://github.com/python-poetry/poetry/issues/5250
  PYTHON_KEYRING_BACKEND: keyring.backends.fail.Keyring

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1
    - run: make sora
  
  lint:
    runs-on: ubuntu-latest
    needs: codegen
    steps:
    - run: poetry install
    - run: make lint

  check-install:
    runs-on: ubuntu-latest
    needs: codegen
    steps:
    - run: pip install .
    - run: sora --version

  wheel:
    runs-on: ubuntu-latest
    needs:
      - codegen
      - lint
      - check-install
    steps:
    - run: poetry build
    