name: Code Formatting and Linting
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      #https://github.com/python-poetry/poetry/issues/5250
      PYTHON_KEYRING_BACKEND: keyring.backends.fail.Keyring
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1
    - run: make sora
    - run: poetry install
    - run: make lint
  
  check-install:
    runs-on: ubuntu-latest
    env:
      #https://github.com/python-poetry/poetry/issues/5250
      PYTHON_KEYRING_BACKEND: keyring.backends.fail.Keyring
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1
    - run: make sora
    - run: pip install .
    - run: sora --version
    