name: Code Formatting and Linting
on:
  push:

env:
  #https://github.com/python-poetry/poetry/issues/5250
  PYTHON_KEYRING_BACKEND: keyring.backends.fail.Keyring

jobs:
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1

    - run: make lint

  pip-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1

    - run: make sora
    - run: pip install .
    - run: sora --version

  wheel:
    runs-on: ubuntu-latest
    needs:
      - lint
      - pip-install
    steps:
    - uses: actions/checkout@v3
    - run: pip install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - uses: bufbuild/buf-setup-action@v1

    - run: |
        poetry version $(poetry version -s)+$(git branch --show-current | tr -d '+~/ ')-$(git rev-parse --short HEAD)
    - run: make wheel

    - uses: actions/upload-artifact@v3
      with:
        name: sora.whl
        path: |
          dist/*.whl
